project:
  type: website

website:
  title: "Data Science & Analytics"
  search: false
  navbar: 
    left: 
      - href: https://mazuckerberg.georgetown.domains/
        text: About me

  sidebar:
    style: "docked"
    search: false
    contents:
      - href: https://github.com/anly501/dsan-5000-project-mazuckerberg-git
        text: Code
      - href: https://github.com/anly501/dsan-5000-project-mazuckerberg-git/tree/main/data
        text: Data
      - href: "1_introduction.qmd"
        text: Introduction
      - href: "2_data_gathering.qmd"
        text: Data Gathering
      - href: "3_data_cleaning.qmd"
        text: Data Cleaning
      - href: "4_data_exploration.qmd"
        text: Data Exploration
      - href: "5_clustering.qmd"
        text: Clustering
      - href: "6_dimensionality_reduction.qmd"
        text: Dimensionality reduction
      - href: "7_decision_trees.qmd"
        text: Decision Trees
      - href: "8_ARM.qmd"
        text: ARM
      - href: "9_conclusions.qmd"
        text: Conclusions

format:
  html:
    theme: minty
    toc: true



