---
title: "Commodity Price"
format: html
---
```{css, echo = FALSE}
.justify {
    text-align: justify !important;
    text-indent: 20px; 
}

.epigrafe {
    text-align: justify !important;
    text-indent: 20px; 
    border: 1.5px solid #87c8b5; 
    padding-top: 15px;
    padding-bottom: 5px;
    padding-right: 15px;
    padding-left: 15px;
    font-size: 14px;
    background-color: #f9f9f9; 
    margin: 20px 0px 30px 0px;
}
```

``` {r}
#| echo: false
#| message: false
#| code-fold: true
#| code-summary: "Libraries"
#| results: 'hide'
#| warning: false

library(tidyverse)
library(ggplot2)
library(forecast)
library(astsa)
library(xts)
library(tseries)
library(fpp2)
library(fma)
library(lubridate)
library(tidyverse)
library(TSstudio)
library(quantmod)
library(tidyquant)
library(plotly)
library(ggplot2)
library(gridExtra)
library(readxl)
library(zoo)
```

### Resources Price

::: {.epigrafe}
Before cleaning the dataset, the dataset had ### rows and # columns:

- ###

- ###

- ###

- ###
:::

``` {r}
#| echo: true
#| message: false
#| code-fold: true
#| code-summary: "Data Gathering"
#| warning: false

# Read csv file
df_commodity_price <- read_excel("../../../data/00-raw-data/commodity_price.xlsx")

# Original dataset
knitr::kable(head(df_commodity_price, n = 10))
```

**Dimensions:**

``` {r}
#| echo: false
#| message: false
#| warning: false

# Dataset dimensions
dim(df_commodity_price)
```

::: {.epigrafe}
Data Cleaning Description. 
:::

``` {r}
#| echo: true
#| message: false
#| code-fold: true
#| code-summary: "Data Cleaning Code"
#| warning: false

df_commodity_price <- read_excel("../../../data/00-raw-data/commodity_price.xlsx")

df_commodity_price <- df_commodity_price %>%
  pivot_longer(cols = -c('...1'), 
               names_to = "Month_Year",
               values_to = "Price")

df_commodity_price <- df_commodity_price %>% filter(!is.na(Price) & Price != "")

df_commodity_price$Month_Year <- as.yearmon(df_commodity_price$Month_Year, format = "%b %Y")

df_commodity_price$Month_Year <- format(df_commodity_price$Month_Year, "%m-%Y")

df_commodity_price$Month_Year <- paste("01-", df_commodity_price$Month_Year, sep = "")

df_commodity_price$Month_Year <- as.Date(df_commodity_price$Month_Year, format = "%d-%m-%Y")

names(df_commodity_price) <- c('Commodity', 'DATE', 'Price')
```

**Cleaned Data:**

::: {.epigrafe}
Data Cleaning Description. 
:::

``` {r}
#| echo: true
#| message: false
#| code-fold: true
#| code-summary: "Data Cleaning"
#| warning: false

df_commodity_price <- df_commodity_price %>% filter(Commodity %in% c("Lithium", "Aluminum", "Cobalt", "Copper", "Nickel", "Zinc"))

df_commodity_price <- pivot_wider(df_commodity_price, id_cols = DATE, names_from = Commodity, values_from = Price)

#df_commodity_price <- df_commodity_price %>% select(Commodity, DATE, Price)

#names(df_commodity_price) <- c('DATE', 'Price')

df_commodity_price <- na.omit(df_commodity_price)
```

**Cleaned Data:**

``` {r}
#| echo: false
#| message: false
#| warning: false

# Cleaned dataset
knitr::kable(tail(df_commodity_price, n = 10))
```

**Summary:**

``` {r}
#| echo: false
#| message: false
#| warning: false

summary(df_commodity_price)
```

**Dimensions:**

``` {r}
#| echo: false
#| message: false
#| warning: false

dim(df_commodity_price)
```

``` {r}
#| echo: false
#| message: false
#| warning: false

# Save dataframe as a new file
write.csv(df_commodity_price, '../../../data/01-modified-data/clean_resources-price.csv', row.names = FALSE)
```