project:
  type: website

website:
  title: "Time Series"
  search: false
  navbar: 
    left: 
      - href: https://mazuckerberg.georgetown.domains/
        text: Home | About me

  sidebar:
    style: "docked"
    search: false
    contents:
      - href: "1_introduction.qmd"
        text: Introduction
      - href: "2_about.qmd"
        text: About Data
      - href: "3_data_sources.qmd"
        text: Data Sources
      - href: "4_data_visualization.qmd"
        text: Data Visualization
      - href: "5_exploratory_data_analysis.qmd"
        text: Exploratory Data Analysis
      - href: "6_ARMA_ARIMA_SARIMA.qmd"
        text: ARMA/ARIMA/SARIMA Models
      - href: "7_ARIMAX_SARIMAX_VAR.qmd"
        text: ARIMAX/SARIMAX/VAR
      - href: "8_Spectral_Analysis_Filtering.qmd"
        text: Spectral Analysis and Filtering (Optional)
      - href: "9_Financial_Time_Series_Models.qmd"
        text: Financial Time Series Models (ARCH/GARCH)
      - href: "10_Deep_Learning_TS.qmd"
        text: Deep Learning for TS
      - href: "11_Conclusions.qmd"
        text: Conclusions
      - href: "dv.qmd"
        text: Data Viz Examples

format:
  html:
    theme: minty
    toc: true

editor: visual

